create type status as enum  ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED');
create type state as enum ('ALL', 'CURRENT', 'FUTURE', 'WAITING', 'REJECTED');

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(100) NOT NULL,
                                     email VARCHAR(100) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(100) NOT NULL,
                                     description VARCHAR(512) NOT NULL,
                                     owner_id BIGINT NOT NULL,
                                     available boolean NOT NULL,
                                     request_id BIGINT,
                                     CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     start timestamp,
                                     finish timestamp,
                                     item_id BIGINT NOT NULL,
                                     booker_id BIGINT NOT NULL,
                                     owner_id BIGINT NOT NULL,
                                     status status,
                                     state state,
                                     CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     description VARCHAR(512),
                                     requestor_id BIGINT NOT NULL,
                                     create_date timestamp,
                                     CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        item_id BIGINT NOT NULL,
                                        booker_id BIGINT NOT NULL,
                                        text VARCHAR,
                                        CONSTRAINT pk_comments PRIMARY KEY (id)
);



